repos:
-   repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
    - id: black
      language_version: python3
      exclude: 'documents'
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      exclude: 'input_data'